#!/usr/bin/env node
// Image-prep pipeline for cloud-hosted imagery.
//
// Reads full-res originals from a masters dir (kept OUT of git). Their tree
// mirrors content paths, so masters/grid/c2.jpg -> key "grid/c2.jpg". For each,
// IN THIS ORDER (order is load-bearing):
//   1. extract IPTC/XMP keywords -> data/imagetags.yaml  (BEFORE stripping, or
//      the keywords are gone)
//   2. clean full-res for CDN upload: `magick <m> -auto-orient -strip` -> writes
//      to dist-images/ (gitignored). -auto-orient bakes rotation into pixels,
//      -strip removes ALL metadata (GPS, serial, timestamps) so nothing private
//      ships to the CDN.
//   3. downscaled preview -> the content bundle (committed for local dev).
//
// Masters are never mutated and never committed; only previews + the tags file
// enter git; clean full-res is uploaded to the CDN, not committed.
//
// Requires `exiftool` and `magick` (ImageMagick) on PATH. Run manually when
// adding photos — NOT part of `pnpm build`.
//
// Usage:
//   pnpm images <mastersDir> [--content dir] [--upload dir] [--data file] [--width px]
// Defaults: content=exampleSite/content  upload=dist-images
//           data=exampleSite/data/imagetags.yaml  width=1200
//   pnpm images --selftest    # run pure-logic checks, no binaries needed

import { execFileSync } from 'node:child_process'
import { mkdirSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { dirname, extname, join, relative } from 'node:path'

const IMG = new Set(['.jpg', '.jpeg', '.png', '.tif', '.tiff', '.webp'])

/** content-relative, forward-slash key: absolute file path -> "grid/c2.jpg" */
export function imageKey(root, file) {
  return relative(root, file).split('\\').join('/')
}

/** serialize { "grid/c2.jpg": ["a","b"] } to flow-style YAML lines */
export function toYaml(map) {
  const head =
    '# Extracted image keywords, keyed by content-relative image path.\n' +
    '# Regenerated by `pnpm images` (scripts/prep-images.mjs).\n'
  const body = Object.keys(map)
    .sort()
    .map((k) => `${k}: [${map[k].join(', ')}]`)
    .join('\n')
  return head + body + '\n'
}

function walk(dir) {
  const out = []
  for (const name of readdirSync(dir)) {
    const p = join(dir, name)
    if (statSync(p).isDirectory()) out.push(...walk(p))
    else if (IMG.has(extname(name).toLowerCase())) out.push(p)
  }
  return out
}

function keywords(file) {
  // -j JSON; -sep merges Keywords + Subject into one comma list per field
  const raw = execFileSync(
    'exiftool',
    ['-j', '-sep', ',', '-Keywords', '-Subject', file],
    {
      encoding: 'utf8'
    }
  )
  const rec = JSON.parse(raw)[0] ?? {}
  const tags = `${rec.Keywords ?? ''},${rec.Subject ?? ''}`
    .split(',')
    .map((t) => t.trim())
    .filter(Boolean)
  return [...new Set(tags)]
}

function selftest() {
  const root = '/site/content'
  console.assert(
    imageKey(root, '/site/content/grid/c2.jpg') === 'grid/c2.jpg',
    'imageKey'
  )
  console.assert(
    toYaml({ 'b/2.jpg': ['x'], 'a/1.jpg': ['p', 'q'] }).includes(
      'a/1.jpg: [p, q]\nb/2.jpg: [x]'
    ),
    'toYaml sorts + flow-style'
  )
  console.log('selftest ok')
}

function main(argv) {
  if (argv.includes('--selftest')) return selftest()

  const opt = (flag, def) => {
    const i = argv.indexOf(flag)
    return i === -1 ? def : argv[i + 1]
  }
  const positional = argv.filter(
    (a, i) => !a.startsWith('--') && !argv[i - 1]?.startsWith('--')
  )
  const mastersDir = positional[0]
  if (!mastersDir) {
    console.error(
      'usage: pnpm images <mastersDir> [--content dir] [--upload dir] [--data file] [--width px]\n' +
        'mastersDir holds your full-res originals (kept OUT of git); their tree mirrors content paths.'
    )
    process.exit(1)
  }
  const contentDir = opt('--content', 'exampleSite/content')
  const uploadDir = opt('--upload', 'dist-images')
  const dataFile = opt('--data', 'exampleSite/data/imagetags.yaml')
  const width = opt('--width', '1200')

  // masters are read-only inputs; key = path relative to mastersDir (e.g. grid/c2.jpg)
  const files = walk(mastersDir)
  const map = {}
  for (const master of files) {
    const key = imageKey(mastersDir, master)
    map[key] = keywords(master)

    // 2. EXIF-stripped full-res -> dist-images/ (gitignored, uploaded to CDN)
    const clean = join(uploadDir, key)
    mkdirSync(dirname(clean), { recursive: true })
    execFileSync('magick', [master, '-auto-orient', '-strip', clean])

    // 3. downscaled preview -> content bundle (committed for local dev)
    const preview = join(contentDir, key)
    mkdirSync(dirname(preview), { recursive: true })
    // `>` = only shrink; never upscale a master narrower than <width>
    execFileSync('magick', [clean, '-resize', `${width}x>`, preview])

    console.log(`${key}  [${map[key].join(', ')}]`)
  }

  mkdirSync(dirname(dataFile), { recursive: true })
  writeFileSync(dataFile, toYaml(map))
  console.log(
    `\n${files.length} images: previews -> ${contentDir}/ (commit), clean masters -> ${uploadDir}/ (upload), tags -> ${dataFile}`
  )
  console.log(
    `Next: upload ${uploadDir}/ to your CDN bucket (e.g. aws s3 sync ${uploadDir}/ s3://<bucket>/), then commit the previews + ${dataFile}.`
  )
}

main(process.argv.slice(2))
